# -----------------------------------------------------------------------------
# Build all portable apps for confirmation
# Author: Urs Roesch https://github.com/uroesch
# Version: 0.2.0
# -----------------------------------------------------------------------------
name: build-all-packages

on:
  push:
    branches:
    - workflow/*
  schedule:
    - cron: '13 13 * * 6' # Run on 1.13pm on Saturdays
  workflow_dispatch:

jobs:
  build-all-packages:
    timeout-minutes: 90
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        os:
        - ubuntu-latest
    env:
      DISPLAY: ':7777'

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: Run build script
      shell: bash
      run: bash scripts/build-all.sh --docker
      timeout-minutes: 90
