# -----------------------------------------------------------------------------
# Build all portable apps for confirmation
# Author: Urs Roesch https://github.com/uroesch
# Version: 0.4.0
# -----------------------------------------------------------------------------
name: build-all-packages

on:
  push:
    branches:
    - workflow/*
  schedule:
    - cron: '13 13 * * 6' # Run on 1.13pm on Saturdays
  workflow_dispatch:

jobs:
  pa-matrix:
    runs-on: ubuntu-latest
    outputs:
      portable-apps: ${{ steps.pa-list.outputs.portable-apps }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: PortableApps list
        id: pa-list
        shell: bash
        run: |
          declare -a list
          list=( $(find . -maxdepth 1 -type d -name "*Portable" -printf "%f\n") )
          printf -v array '"%s",'  "${list[@]}"
          printf "portable-apps={\"portable-app\":[${array%%,}]}" >> ${GITHUB_OUTPUT}


  build:
    needs:
      - pa-matrix
    timeout-minutes: 90
    runs-on: ubuntu-latest
    container:
      image: uroesch/pa-wine:latest
      env:
        RUN_AS_ROOT: yes
    strategy:
      max-parallel: 10
      fail-fast: true
      matrix: ${{ fromJSON(needs.pa-matrix.outputs.portable-apps) }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Run build script via docker
      shell: bash
      run: |
        cd ${{ matrix.portable-app }} && \
        /entrypoint.sh \
          /usr/bin/pwsh -ExecutionPolicy ByPass \
          Other/Update/Update.ps1 -InfraDir /pa-build
      timeout-minutes: 10
